# Generated by Django 6.0.3 on 2026-06-26 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_category_options_alter_category_cat_image_and_more'),
        ('store', '0005_rename_is_avaliable_product_is_available'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'Imagem da Galeria', 'verbose_name_plural': 'Galeria de Fotos dos Produtos'},
        ),
        migrations.AlterModelOptions(
            name='reviewrating',
            options={'verbose_name': 'Avaliação e Nota', 'verbose_name_plural': 'Avaliações e Notas'},
        ),
        migrations.AlterModelOptions(
            name='variation',
            options={'verbose_name': 'Variação', 'verbose_name_plural': 'Variações'},
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.FloatField(default=2.0, help_text='Altura em centímetros'),
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.FloatField(default=16.0, help_text='Comprimento em centímetros'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.FloatField(default=0.3, help_text='Peso em Quilogramas (Ex: 0.5 para 500g)'),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.FloatField(default=11.0, help_text='Largura em centímetros'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(upload_to='photos/products', verbose_name='Imagem Principal'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Disponível'),
        ),
        migrations.AlterField(
            model_name='product',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Modificação'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nome do Produto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Slug (Link Único)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(verbose_name='Estoque'),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='image',
            field=models.ImageField(max_length=255, upload_to='store/products', verbose_name='Imagem da Galeria'),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='ip',
            field=models.CharField(blank=True, max_length=20, verbose_name='Endereço IP'),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='rating',
            field=models.FloatField(verbose_name='Nota'),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='review',
            field=models.TextField(blank=True, max_length=500, verbose_name='Avaliação'),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status (Visível)'),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='subject',
            field=models.CharField(blank=True, max_length=100, verbose_name='Assunto'),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='created_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('color', 'Cor'), ('size', 'Tamanho')], max_length=100, verbose_name='Tipo de Variação'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='variation_value',
            field=models.CharField(max_length=100, verbose_name='Valor da Variação'),
        ),
    ]
