# Generated by Django 6.0.3 on 2026-06-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_product_height_remove_product_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.FloatField(default=2.0),
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.FloatField(default=16.0),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.FloatField(default=0.3),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.FloatField(default=11.0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
