# Generated by Django 6.0.3 on 2026-07-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_shipping_class_alter_product_height_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Título do Banner')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Imagem')),
                ('alt_text', models.CharField(blank=True, max_length=150, verbose_name='Texto Alternativo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
