# Generated by Django 6.0.3 on 2026-07-01 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_banner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
