# Generated by Django 6.0.3 on 2026-07-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código do Cupom')),
                ('discount_type', models.CharField(choices=[('percentage', 'Porcentagem (%)'), ('fixed', 'Valor Fixo (R$)'), ('free_shipping', 'Frete Grátis')], max_length=20, verbose_name='Tipo de Desconto')),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor do Desconto')),
                ('min_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Mínimo do Pedido')),
                ('max_uses', models.IntegerField(default=0, verbose_name='Limite de Usos (0 = ilimitado)')),
                ('used_count', models.IntegerField(default=0, verbose_name='Usos Realizados')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('valid_from', models.DateTimeField(verbose_name='Válido de')),
                ('valid_until', models.DateTimeField(verbose_name='Válido até')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cupom',
                'verbose_name_plural': 'Cupons',
            },
        ),
    ]
