# Generated by Django 6.0.3 on 2026-07-10 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=50, verbose_name='Sobrenome')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Nome de Usuário')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Endereço de E-mail')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Número de Telefone')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('last_login', models.DateTimeField(auto_now_add=True, verbose_name='Último Login')),
                ('is_admin', models.BooleanField(default=False, verbose_name='É Administrador')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Equipe (Staff)')),
                ('is_active', models.BooleanField(default=False, verbose_name='Ativo')),
                ('is_superadmin', models.BooleanField(default=False, verbose_name='Super Administrador')),
            ],
            options={
                'verbose_name': 'Conta de Usuário',
                'verbose_name_plural': 'Contas de Usuários',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(blank=True, max_length=100, verbose_name='Endereço Linha 1')),
                ('address_line_2', models.CharField(blank=True, max_length=100, verbose_name='Endereço Linha 2 (Opcional)')),
                ('profile_picture', models.ImageField(blank=True, upload_to='userprofile', verbose_name='Foto de Perfil')),
                ('city', models.CharField(blank=True, max_length=20, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, max_length=20, verbose_name='Estado')),
                ('country', models.CharField(blank=True, max_length=20, verbose_name='País')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
            },
        ),
    ]
