# Generated by Django 6.0.3 on 2026-07-10 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_create_admin'),
        ('accounts', '0003_alter_account_options_alter_userprofile_options_and_more'),
    ]

    operations = [
    ]
