# Generated by Django 6.0.3 on 2026-06-28 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_shipping_cost_order_shipping_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tax',
        ),
    ]
