# Generated by Django 6.0.3 on 2026-06-29 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_order_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='label_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID da Etiqueta'),
        ),
        migrations.AddField(
            model_name='order',
            name='label_url',
            field=models.URLField(blank=True, verbose_name='PDF da Etiqueta'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_company',
            field=models.CharField(blank=True, max_length=100, verbose_name='Transportadora'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_company_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID da Transportadora'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='Prazo de Entrega'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_service_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID do Serviço'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=100, verbose_name='Código de Rastreio'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_url',
            field=models.URLField(blank=True, verbose_name='Link de Rastreio'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor do Frete'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(blank=True, max_length=100, verbose_name='Serviço'),
        ),
    ]
