# Generated by Django 6.0.3 on 2026-06-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_label_id_order_label_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cep',
            field=models.CharField(default=0, max_length=9, verbose_name='CEP'),
            preserve_default=False,
        ),
    ]
