# Generated by Django 6.0.3 on 2026-07-03 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_cep'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cpf',
            field=models.CharField(default=0, max_length=14, verbose_name='CPF'),
            preserve_default=False,
        ),
    ]
