# Generated by Django 6.0.3 on 2026-07-03 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
    ]
