# Generated by Django 6.0.3 on 2026-07-06 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_label_pdf',
            field=models.FileField(blank=True, null=True, upload_to='etiquetas/', verbose_name='PDF da Etiqueta'),
        ),
    ]
