# Generated by Django 6.0.3 on 2026-07-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_shipping_label_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='label_url',
            field=models.URLField(blank=True, verbose_name='Link da Etiqueta no Painel'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_label_pdf',
            field=models.FileField(blank=True, null=True, upload_to='etiquetas/', verbose_name='Arquivo PDF da Etiqueta'),
        ),
    ]
