# Generated by Django 6.0.3 on 2026-07-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_order_label_url_alter_order_shipping_label_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'Novo'), ('Pending', 'Aguardando Pagamento'), ('Accepted', 'Pagamento Aprovado'), ('Preparing', 'Preparando Pedido'), ('Shipped', 'A Caminho'), ('Delivered', 'Entregue'), ('Completed', 'Concluído'), ('Cancelled', 'Cancelado')], default='Pending', max_length=10, verbose_name='Status do Pedido'),
        ),
    ]
