# Generated by Django 6.0.3 on 2026-07-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancellation_reason',
            field=models.TextField(blank=True, verbose_name='Motivo do Cancelamento'),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID do Reembolso'),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_status',
            field=models.CharField(blank=True, max_length=20, verbose_name='Status do Reembolso'),
        ),
    ]
